[workspace]
resolver = "2"
members = [
    "cli",
    "gen",
    "lib",
    "example",
    "sort",
    "test"
]

[workspace.dependencies]
bincode = { version = "2.0.0-rc.3", features = ["serde"] }
chrono = "0.4"
lazy_static = "1"
parquet = "51"
thiserror = "1"
