[package]
name = "parquetry-cli"
version = "0.7.0"
edition = "2021"

[dependencies]
cli-helpers = "0.1"
parquet = { workspace = true }
parquetry-gen = { path = "../gen/" }
thiserror = { workspace = true }
