[package]
name = "parquetry-gen"
version = "0.1.0"
edition = "2021"
authors = ["Travis Brown <travisrobertbrown@gmail.com>"]
homepage = "https://github.com/travisbrown/parquetry"
repository = "https://github.com/travisbrown/parquetry"
description = "Parquet code generator"
keywords = ["parquet"]
license-file = "../LICENSE"
readme = "../README.md"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
codegen = "0.2"
convert_case = "0.6"
lazy_static = "1"
parquet = "46"
prettyplease = "0.2"
syn = "2"
thiserror = "1"

[features]
default = ["serde"]
serde = []