[package]
name = "parquetry-gen"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
codegen = "0.2"
convert_case = "0.6"
lazy_static = "1"
parquet = "46"
prettyplease = "0.2"
syn = "2"
thiserror = "1"
