[package]
name = "parquetry-gen"
description = "Parquet code generator"
keywords = ["parquet"]
authors = { workspace = true }
repository = { workspace = true }
version = { workspace = true }
edition = { workspace = true }
license-file = { workspace = true }
readme = { workspace = true }

[dependencies]
codegen = "0.2"
convert_case = "0.8"
parquet = { workspace = true }
prettyplease = "0.2"
syn = "2"
thiserror = { workspace = true }
