[package]
name = "parquetry-gen"
version = "0.7.0"
edition = "2021"
authors = ["Travis Brown <travisrobertbrown@gmail.com>"]
homepage = "https://github.com/travisbrown/parquetry"
repository = "https://github.com/travisbrown/parquetry"
description = "Parquet code generator"
keywords = ["parquet"]
license-file = "../LICENSE"
readme = "../README.md"

[dependencies]
codegen = "0.2"
convert_case = "0.6"
lazy_static = { workspace = true }
parquet = { workspace = true }
prettyplease = "0.2"
syn = "2"
thiserror = { workspace = true }
